app/accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
        
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url='/accounts/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('', include('website.urls')),
    path('dashboards/', include(('dashboards.urls', 'dashboards'), namespace='dashboards')),
    path('accounts/', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/dashboards/urls.py
from django.urls import path
from . import views
from .dashboards import dashboard

app_name = 'dashboards'
urlpatterns = [
    path('', views.index, name='index'),
]

app/website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index.html', views.index, name='index'),
    path('about.html', views.about, name='about'),
    path('contact.html', views.contact, name='contact'),
    path('pricing.html', views.pricing, name='pricing'),
    path('faq.html', views.faq, name='faq'),
    path('blog-home.html', views.blog_home, name='blog-home'),
    path('blog-post.html', views.blog_post, name='blog-post'),
    path('portfolio-overview.html', views.portfolio_overview, name='portfolio-overview'),
    path('portfolio-item.html', views.portfolio_item, name='portfolio-item'),
    
]

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["username"]

app/dashboards/models.py
from django.db import models

# Create your models here.

app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from.models import User

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()

app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import PasswordResetForm
from .forms import LoginForm
from django.contrib import messages
from django.urls import reverse
from .models import User

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

import os

# Create your views here.
def log_in(request):

    if request.user.is_authenticated:
        return redirect('dashboards:index')
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            # We check if the data is correct
            user = authenticate(email=email, password=password)
            if user:  # If the returned object is not None
                login(request, user)  # we connect the user
                messages.success(request, "Bem-vindo " + str(user))
                return redirect('dashboards:index')
            else:  # otherwise an error will be displayed
                messages.error(request, 'Email ou senha inválida')
    else:
        form = LoginForm()

    return render(request, 'accounts/login.html', {'form': form})


def log_out(request):
    logout(request)

    return redirect(reverse('accounts:login'))


def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Recuperar senha acesso ao Dashboard da Divisão de Soluções para Campus Inteligente - DSCI"
					email_template_name = "accounts/password_reset_email.html"
					c = {
					"email":user.email,
					'domain':os.getenv('DOMAIN'),
					'site_name': 'Dashboard - Divisão de Soluções para Campus Inteligente',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, os.getenv('EMAIL_HOST_USER'), [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("done/")
					
	password_reset_form = PasswordResetForm()
	return render(request, 'accounts/password_reset.html', {'password_reset_form': password_reset_form})
    

app/dashboards/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
#@login_required
def index(request):
    return render(request, 'dashboards/index.html')

app/website/views.py
from django.shortcuts import render

def index(requests):
    return render(requests,'website/index.html')

def about(requests):
    return render(requests,'website/about.html')

def contact(requests):
    return render(requests,'website/contact.html')

def pricing(requests):
    return render(requests,'website/pricing.html')

def faq(requests):
    return render(requests,'website/faq.html')

def blog_home(requests):
    return render(requests,'website/blog-home.html')

def blog_post(requests):
    return render(requests,'website/blog-post.html')

def portfolio_overview(requests):
    return render(requests,'website/portfolio-overview.html')

def portfolio_item(requests):
    return render(requests,'website/portfolio-item.html')

app/accounts/templates/accounts/login.html
{% extends "base_generic.html" %}
{% load static %}

{% block header %}
    <link rel="icon" type="image/x-icon" href="{% static 'accounts/images/favicon.ico' %}" />
    <link href="{% static 'accounts/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock header %}

{% block content %}
<div class="container">
  <div class="login">
    <div class="row">
        <div class="col-12">
        <h2 class="mt-2 mb-4">Acesse o Dashboard da DSCI</h2>
        <form method="post">
            {% csrf_token %}

            <div class="form-group">
            <label for="id_email">Email:</label><br>
            <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
                name="email" value='{{ form.email.value|default:"" }}'>
            {% if form.email.errors %}
            <div class="invalid-feedback">{{ form.email.errors }}</div>
            {% endif %}
            </div>

            <div class="form-group">
            <label for="id_password">Senha:</label><br>
            <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}"
                id="id_password" name="password" value='{{ form.password.value|default:"" }}'>
            {% if form.password.errors %}
            <div class="invalid-feedback">{{ form.password.errors }}</div>
            {% endif %}
            </div>

            <button type="submit" class="btn btn-primary col-12">Entrar</button>
        </form>
          <br>
          <p>Esqueceu a senha? <a href="{% url 'accounts:password_reset' %}">Clique aqui</a></p>
        </div>
    </div>
  </div>
  <div class="footer">
        {% comment %} <a href="http://ufrpe.br" target="_blank">
                <img id="ufrpe-digital" src="{% static 'accounts/images/UFRPE-Digital-08.png' %}">
        </a> {% endcomment %}
        <a href="http://www.nti.ufrpe.br" target="_blank">
                <img id="logo-std" src="{% static 'accounts/images/std_amarelo_transparente.png' %}">
        </a>
  </div>
</div>
{% endblock content %}

app/accounts/templates/accounts/logout.html
{% extends "base_generic.html" %}

{% block content %}
  <p>Sessão encerrada!</p>
  <a href="{% url 'login'%}">Clique aqui para logar novamente.</a>
{% endblock %}

app/accounts/templates/accounts/password_reset.html
{% extends "base_generic.html" %}
{% load static %}

{% block header %}
    <link rel="icon" type="image/x-icon" href="{% static 'accounts/images/favicon.ico' %}" />
    <link href="{% static 'accounts/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock header %}

{% block head_title %}Recuperar Senha{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="login">
    <div class="row">
        <div class="col-12">
        <h2 class=" my-12">Recuperar Senha</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
            <label for="id_email">Email:</label><br>
            <input type="email" class="form-control" id="id_email" name="email" placeholder="entre com seu email" value='{{ form.email.value|default:"" }}'>
            </div>

            <button type="submit" class="btn btn-primary col-12">Recuperar Senha</button>
        </form>
        </div>
    </div>
  </div>
    <div class="footer">
        {% comment %} <a href="http://ufrpe.br" target="_blank">
                <img id="ufrpe-digital" src="{% static 'accounts/images/UFRPE-Digital-08.png' %}">
        </a> {% endcomment %}
        <a href="http://www.nti.ufrpe.br" target="_blank">
                <img id="logo-std" src="{% static 'accounts/images/std_amarelo_transparente.png' %}">
        </a>
  </div>
</div>
{% endblock content %}

app/accounts/templates/accounts/password_reset_complete.html
{% extends "base_generic.html" %}
{% load static %}

{% block header %}
    <link rel="icon" type="image/x-icon" href="{% static 'accounts/images/favicon.ico' %}" />
    <link href="{% static 'accounts/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock header %}

{% block head_title %}Recuperar Senha{% endblock head_title %}

{% block content %}
<div class="container">
  <div class='login'>
    <div class="row">
        <div class="col-12">
        <h2 class="my-5">Senha Alterada com Sucesso!</h2>
        <p>
            Sua senha foi alterada com sucesso. 
            <a href="{% url 'accounts:login' %}">Logar.</a>
        </p>
        </div>
    </div>
  </div>
    <div class="footer">
        {% comment %} <a href="http://ufrpe.br" target="_blank">
                <img id="ufrpe-digital" src="{% static 'accounts/images/UFRPE-Digital-08.png' %}">
        </a> {% endcomment %}
        <a href="http://www.nti.ufrpe.br" target="_blank">
                <img id="logo-std" src="{% static 'accounts/images/std_amarelo_transparente.png' %}">
        </a>
  </div>
</div>
{% endblock content %}

app/accounts/templates/accounts/password_reset_confirm.html
{% extends "base_generic.html" %}
{% load static %}

{% block header %}
    <link rel="icon" type="image/x-icon" href="{% static 'accounts/images/favicon.ico' %}" />
    <link href="{% static 'accounts/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock header %}

{% block head_title %}Recuperar Senha{% endblock head_title %}

{% block content %}
<div class="container">
  <div class='login'>
    <div class="row">
        <div class="col-12">
        <h2 class=" my-3">Alterar Senha</h2>
        {% if validlink %}
        <div class="row">
            <form class="col-12" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.new_password1.label_tag }}
                <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
                id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>
                {% if form.new_password1.errors %}
                <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.new_password2.label_tag }}
                <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
                id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>
                {% if form.new_password2.errors %}
                <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary col-12">Alterar</button>
            </form>
        </div>
        {% else %}
        <p>
            O link não é válido, possivelmente esse link já foi utilizado. Por favor, requisite um 
            <a href="{% url 'accounts:password_reset' %}">novo link por email.</a>
        </p>
        {% endif %}
        </div>
    </div>
  </div>
    <div class="footer">
       {% comment %}  <a href="http://ufrpe.br" target="_blank">
                <img id="ufrpe-digital" src="{% static 'accounts/images/UFRPE-Digital-08.png' %}">
        </a> {% endcomment %}
        <a href="http://www.nti.ufrpe.br" target="_blank">
                <img id="logo-std" src="{% static 'accounts/images/std_amarelo_transparente.png' %}">
        </a>
  </div>
</div>
{% endblock content %}

app/accounts/templates/accounts/password_reset_done.html
{% extends "base_generic.html" %}
{% load static %}

{% block header %}
    <link rel="icon" type="image/x-icon" href="{% static 'accounts/images/favicon.ico' %}" />
    <link href="{% static 'accounts/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock header %}

{% block head_title %}Recuperar Senha{% endblock head_title %}

{% block content %}
<div class="container">
  <div class='login'>
    <div class="row">
        <div class=" col-12">
        <h2 class="my-5">Recuperar Senha</h2>
        <p>
            Enviamos para você instruções para redefinir sua senha, se houver uma conta com o e-mail que você digitou, você deve recebê-las em breve.
        </p>
        <p>
            Se você não recebeu um e-mail, certifique-se de inserir o endereço com o qual se inscreveu e também verifique sua pasta de spam.
        </p>
        </div>
    </div>
  </div>
    <div class="footer">
       {% comment %}  <a href="http://ufrpe.br" target="_blank">
                <img id="ufrpe-digital" src="{% static 'accounts/images/UFRPE-Digital-08.png' %}">
        </a> {% endcomment %}
        <a href="http://www.nti.ufrpe.br" target="_blank">
                <img id="logo-std" src="{% static 'accounts/images/std_amarelo_transparente.png' %}">
        </a>
  </div>
</div>
{% endblock content %}

app/accounts/templates/accounts/password_reset_email.html
Olá,

Para recuperar a senha do usuário {{ user.username }}, clique no link abaixo:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

Se o link acima não funcionar, por favor copie e cole a URL numa nova aba ou janela do navegador.

Atenciosamente,
Divisão de Soluções para Campus Inteligente - DSCI
Universidade Federal Rural de Pernambuco - UFRPE

app/dashboards/templates/dashboards/index.html
{% extends "base_generic.html" %}
{% load static %}
{% load plotly_dash %}

{% block header %}
    {% plotly_header %}
    <link rel="icon" type="image/x-icon" href="{% static 'dashboards/images/favicon.ico' %}" />
    <link href="{% static 'dashboards/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock header %}

{% block content %}
    <div>
        <a id="logout" href="{% url 'accounts:logout' %}" class="btn btn-danger" role="button"> <i class="fas fa-sign-out-alt"></i> SAIR</a>
    </div>
    <div style="clear:both;"></div>
    <div class="{% plotly_class name='dsci_dashboard' %}">
        {% plotly_direct name="dsci_dashboard" %}
    </div>
{% endblock content %}

{% block footer %}
    {% plotly_footer %}
{% endblock footer %}

app/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    {% block header %}{% endblock header %}

    <!-- Custom fonts for this template-->
      <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet">

      <script src="https://cdn.plot.ly/plotly-2.4.2.min.js"></script>

    <title>{% block head_title %}Dashboard - Divisão de Soluções para Campus Inteligente - DSCI - STD{% endblock %}</title>

  </head>

  <body>
  {% for message in messages %}    
      <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>
  {% endfor %}

    {% block content %}{% endblock content %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"></script>


      {% block footer %}
      {% endblock footer %}

  </body>
</html>

app/website/templates/website/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Modern Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'website/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'website/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container px-5">
                    <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="about.html">About</a></li>
                            <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
                            <li class="nav-item"><a class="nav-link" href="pricing.html">Pricing</a></li>
                            <li class="nav-item"><a class="nav-link" href="faq.html">FAQ</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                    <li><a class="dropdown-item" href="blog-home.html">Blog Home</a></li>
                                    <li><a class="dropdown-item" href="blog-post.html">Blog Post</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Portfolio</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="portfolio-overview.html">Portfolio Overview</a></li>
                                    <li><a class="dropdown-item" href="portfolio-item.html">Portfolio Item</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Header-->
            <header class="py-5">
                <div class="container px-5">
                    <div class="row justify-content-center">
                        <div class="col-lg-8 col-xxl-6">
                            <div class="text-center my-5">
                                <h1 class="fw-bolder mb-3">Our mission is to make building websites easier for everyone.</h1>
                                <p class="lead fw-normal text-muted mb-4">Start Bootstrap was built on the idea that quality, functional website templates and themes should be available to everyone. Use our open source, free products, or support us by purchasing one of our premium products or services.</p>
                                <a class="btn btn-primary btn-lg" href="#scroll-target">Read our story</a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- About section one-->
            <section class="py-5 bg-light" id="scroll-target">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Our founding</h2>
                            <p class="lead fw-normal text-muted mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto est, ut esse a labore aliquam beatae expedita. Blanditiis impedit numquam libero molestiae et fugit cupiditate, quibusdam expedita, maiores eaque quisquam.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- About section two-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Growth &amp; beyond</h2>
                            <p class="lead fw-normal text-muted mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto est, ut esse a labore aliquam beatae expedita. Blanditiis impedit numquam libero molestiae et fugit cupiditate, quibusdam expedita, maiores eaque quisquam.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Team members section-->
            <section class="py-5 bg-light">
                <div class="container px-5 my-5">
                    <div class="text-center">
                        <h2 class="fw-bolder">Our team</h2>
                        <p class="lead fw-normal text-muted mb-5">Dedicated to quality and your success</p>
                    </div>
                    <div class="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Ibbie Eckart</h5>
                                <div class="fst-italic text-muted">Founder &amp; CEO</div>
                            </div>
                        </div>
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Arden Vasek</h5>
                                <div class="fst-italic text-muted">CFO</div>
                            </div>
                        </div>
                        <div class="col mb-5 mb-5 mb-sm-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Toribio Nerthus</h5>
                                <div class="fst-italic text-muted">Operations Manager</div>
                            </div>
                        </div>
                        <div class="col mb-5">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Malvina Cilla</h5>
                                <div class="fst-italic text-muted">CTO</div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-dark py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Your Website 2021</div></div>
                    <div class="col-auto">
                        <a class="link-light small" href="#!">Privacy</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Terms</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'website/js/scripts.js' %}"></script>
    </body>
</html>